# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Agzs"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/arxiv-daily.json'
json_gitpage_path: './docs/arxiv-daily-web.json'
json_wechat_path: './docs/arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "blockchain":
        filters: ["Blockchain", "BlockChain", "blockchain", "DLT", "Distributed ledger", "Smart Contract", "smart contracts", "cryptocurrencies"]
    "crosschain":
        filters: ["Atomic Swap", "interoperability", "cross-chain", "cross chain", "cross blockchain"]
    "zero-knowledge-proof":
        filters: ["Zero-Knowledge Proof", "Zero Knowledge Proof", "zk-SNARK"]
    "secureaggregation":
        filters: ["Secure Aggregation", "Federated Learning", "Privacy Preserving"]
    # "Applied Cryptography":
    #     filters: ["", ""]
    
